/** SO YOUNG / 8world O-Level oral practice sets.
 * Source: https://soyoung.8world.com/topic/gaojihuawengaonianjikoushilianxi
 * Videos embed via Brightcove in-app. Where the original oral hero clip was
 * unpublished, a topic-matched public 8world news clip is used instead.
 */
export type OLevelOralSet = {
  id: number;
  title: string;
  description: string;
  mainQuestion: string;
  questions: string[];
  videoUrl: string;
  sourceUrl: string;
  hasEmbeddedVideo: boolean;
};

export const OLEVEL_ORAL_SETS: OLevelOralSet[] = [
  {
    id: 1,
    title: '本地年长者对健康知识掌握不足',
    description: '你认为我国年长者掌握的健康知识足够吗？',
    mainQuestion: '你认为我国年长者掌握的健康知识足够吗？',
    questions: [
      '你为什么会同意报告中受访者提到“大多数的病患比较难说出所吃的药物名字，也很难正确地指出药剂量”呢？',
      '你在报告中也提到，受访者说大约有三分之二的年长者健康知识掌握不足，这挺让人担忧。你可以进一步加以说明吗？',
      '你认为要怎么样提高年长者的健康知识呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6341824559112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-seniors-medication-literacy-2941811',
    hasEmbeddedVideo: true,
  },
  {
    id: 2,
    title: '气候变化防洪人人有责',
    description: '预防洪灾是每个人的责任。你同意吗？',
    mainQuestion: '预防洪灾是每个人的责任。你同意吗？',
    questions: [
      '你本身是否经历过洪灾？为什么洪灾很可怕？',
      '你认为新加坡人对洪灾有足够的防范意识吗？从哪里可以看出来？',
      '政府和社区可以采取哪些措施来更好地预防和应对洪灾？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6364231583112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-climate-change-flooding-situation-management-2941151',
    hasEmbeddedVideo: true,
  },
  {
    id: 3,
    title: '助特需人士积极融入社区',
    description: '特需人士也可以为社会做出贡献。你同意吗？',
    mainQuestion: '特需人士也可以为社会做出贡献。你同意吗？',
    questions: [
      '以咖啡座这位聋哑店员的例子来看，你觉得他在那里工作可能会碰到什么问题呢？',
      '新闻里提到一家社会企业HeySprouts，创办人伍淑慧为什么要做这件事？你有什么看法呢？',
      '如果你有一位有特需的同学，你会怎么帮助他呢？请举例说明？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6363476977112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-social-enterprise-heysprouts-hires-and-trains-people-with-special-need-2935541',
    hasEmbeddedVideo: true,
  },
  {
    id: 4,
    title: '减少食物浪费意识提升',
    description: '我们可以如何减少食物浪费？',
    mainQuestion: '我们可以如何减少食物浪费？',
    questions: [
      '关于如何减少食物浪费，你提到个人和家庭层面。你可以进一步说明你或你的家人是怎么做的吗？',
      '视频里提到店家利用剩余食物应用程序来减少食物浪费，你对这个做法有什么看法？',
      '谈了这么多，减少食物浪费到底为什么那么重要呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6364744317112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-food-rescue-app-2893756',
    hasEmbeddedVideo: true,
  },
  {
    id: 5,
    title: '童年不良经历影响深远',
    description: '为什么童年不良经历值得关注？',
    mainQuestion: '为什么童年不良经历值得关注？',
    questions: [
      '视频中受访的心理学家有什么看法？心理卫生学院有什么应对的计划？',
      '如果一名少年正在面对不良经历，你认为他会表现出哪些迹象呢？',
      '如果你留意到身边的同学有遭受不良经历的迹象，你会怎么做？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6363228196112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-adverse-childhood-experiences-2890326',
    hasEmbeddedVideo: true,
  },
  {
    id: 6,
    title: '新加坡严厉打击毒品',
    description: '新加坡严厉打击毒品。请简述我国的毒品政策？',
    mainQuestion: '新加坡严厉打击毒品。请简述我国的毒品政策？',
    questions: [
      '你可以说一下中央肃毒局有哪些针对年轻人的预防项目吗？',
      '从新闻内容来看，你得到怎样的体会？',
      '根据你所知道的，青少年吸毒是受什么影响？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6362438332112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-synthetic-drug-testing-2876676',
    hasEmbeddedVideo: true,
  },
  {
    id: 7,
    title: '青少年的心理健康问题',
    description: '青少年应该如何保持良好的心理健康？',
    mainQuestion: '青少年应该如何保持良好的心理健康？',
    questions: [
      '你在报告的结尾提到写日记来记录让自己感恩的事情。这是很有趣的想法，你可以补充说明吗？',
      '视频中提到的调查有什么样的发现？',
      '假设你的朋友因为考试压力太大而向你倾诉，你会怎么开导他呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6362158698112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-youth-mental-health-issue-2863356',
    hasEmbeddedVideo: true,
  },
  {
    id: 8,
    title: '阿卡夫湖重现比达达利公园',
    description: '你理想中的住宅区和市镇是怎样的？',
    mainQuestion: '你理想中的住宅区和市镇是怎样的？',
    questions: [
      '新加坡有哪个市镇比较接近你理想中的市镇呢？',
      '比达达利公园和阿卡夫湖分别有什么特点？',
      '你对阿卡夫湖的设计有什么看法？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6361441040112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-alkaff-lake-2846986',
    hasEmbeddedVideo: true,
  },
  {
    id: 9,
    title: '政府鼓励年长者“就地养老”',
    description: '你认为政府为鼓励年长者就地养老所做的准备工作足够吗？为什么？',
    mainQuestion: '你认为政府为鼓励年长者就地养老所做的准备工作足够吗？为什么？',
    questions: [
      '听完这个新闻后，你对政府为年长者就地养老所做的翻新工作有什么感受？为什么？',
      '除了新闻中提到的翻新设施，你认为还可以增添哪些设施或服务，来进一步帮助年长者更好地在社区养老？',
      '你认为社区翻新的乐龄设施是否能有效缓解新加坡老龄化带来的社会问题？为什么？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6360985541112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-silver-upgrading-programme-2797016',
    hasEmbeddedVideo: true,
  },
  {
    id: 10,
    title: '政府推出社区关系处试点计划',
    description: '我们该如何维护和睦的邻里关系？',
    mainQuestion: '我们该如何维护和睦的邻里关系？',
    questions: [
      '你在报告中的最后一点提到，因为族群、宗教及文化背景不同，生活习惯也会不一样，但是我们应该有包容的心态，互相理解。你可以举一些例子来补充说明吗？',
      '政府为什么要设立社区关系处？它的作用是什么？',
      '如果你碰到邻居发出噪音，你会怎么处理？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6360305317112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-community-disputes-management-framework-enhancements-2790471',
    hasEmbeddedVideo: true,
  },
  {
    id: 11,
    title: '本地独立影院整体票房提升',
    description: '播放非主流影片独立影院的票房比播放主流电影影院的票房来得好。你同意吗？为什么？',
    mainQuestion: '播放非主流影片独立影院的票房比播放主流电影影院的票房来得好。你同意吗？为什么？',
    questions: [
      '既然主流电影能在串流平台看到，为什么还是有人要上影院看呢？',
      '你提到播放非主流影片的独立影院举办和电影相关课题的讨论和对话会能给观众比较完整的经验。请你进一步说明？',
      '你会选择观赏主流或非主流影片？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6351304690112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-independent-cinema-2753711',
    hasEmbeddedVideo: true,
  },
  {
    id: 12,
    title: '圣诺哥渔港正式走入历史',
    description: '你认为把圣诺哥渔港的鱼商搬到裕廊渔港去继续营业，是妥善的安排吗？',
    mainQuestion: '你认为把圣诺哥渔港的鱼商搬到裕廊渔港去继续营业，是妥善的安排吗？',
    questions: [
      '为什么你说“良性竞争，对所有鱼商都有好处”呢？',
      '你认为新来的渔商应该怎么样努力去适应新环境？',
      '针对归还给政府的圣诺哥渔港的土地的发展，你有什么建议呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6349233975112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-jurong-fish-port-2731381',
    hasEmbeddedVideo: true,
  },
  {
    id: 13,
    title: '国人的存款足以应付半年开销吗？',
    description: '储蓄非常重要。你同意吗？',
    mainQuestion: '储蓄非常重要。你同意吗？',
    questions: [
      '你在报告中的第一点提到紧急情况，请你补充说明这些是指什么？',
      '视频提到的调查发现，三分之一受访的国人认为没有足以应付至少半年生活开销的存款。你认为这会造成什么影响？',
      '视频也提到，有不少人认为冷气是必需品，你怎么看呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6357735749112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-singaporeans-savings-and-spending-2717546',
    hasEmbeddedVideo: true,
  },
  {
    id: 14,
    title: '青年文化遗产蓝图',
    description: '“国家文物局举办活动很注重青年的意见。”你同意这样的说法吗？',
    mainQuestion: '“国家文物局举办活动很注重青年的意见。”你同意这样的说法吗？',
    questions: [
      '你会有兴趣参观新闻中提到的“青春有你真好”的巡回展览吗？为什么？',
      '你认为如何进一步吸引年轻人参与文化遗产活动？',
      '新闻中提到“为了确保文化遗产能够代代相传，青年扮演着很重要的角色。”你同意吗？为什么？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6353870475112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-youth-heritage-blueprint-2701256',
    hasEmbeddedVideo: true,
  },
  {
    id: 15,
    title: '你听过“净零排放”吗？',
    description: '“大多数人愿意采取行动支持环保实践。”你同意这样的说法吗？',
    mainQuestion: '“大多数人愿意采取行动支持环保实践。”你同意这样的说法吗？',
    questions: [
      '除了新闻中的环保实践方法，你生活中还会有哪些环保的行为？',
      '你觉得可以如何鼓励年轻人多为环保多尽一份力？',
      '“净零排放目标是实现可持续发展的有效途径。”你同意吗？为什么？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6352950446112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-net-zero-carbon-emissions-2686496',
    hasEmbeddedVideo: true,
  },
  {
    id: 16,
    title: '如何成为优秀野生动物摄影师？',
    description: '成为一名优秀的野生动物摄影师，需要具备哪些素质？',
    mainQuestion: '成为一名优秀的野生动物摄影师，需要具备哪些素质？',
    questions: [
      '看了这则新闻，你有兴趣成为野生动物动物摄影师吗？为什么？',
      '你觉得可以如何培养学生的毅力？',
      '有人认为“现在的新加坡的年轻人都太娇生惯养了，不能吃苦。”你同意吗？为什么？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6350915917112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-recognised-wildlife-photographer-2626931',
    hasEmbeddedVideo: true,
  },
  {
    id: 17,
    title: '我国首两位“女蛙人”毕业了！',
    description: '女性不是弱者，你同意吗？',
    mainQuestion: '女性不是弱者，你同意吗？',
    questions: [
      '你在报告中提到不少家庭取得了男女平等。请你补充说明一下这是指什么？',
      '这两名女蛙人的故事对你有什么启发？',
      '在你身边，哪一位女性最值得尊敬？为什么？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6350509472112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-female-naval-combat-divers-2615681',
    hasEmbeddedVideo: true,
  },
  {
    id: 18,
    title: '义安理工学院新生必修可持续发展课程',
    description: '可持续发展（sustainable development）是什么？我们为什么应该重视它？',
    mainQuestion: '可持续发展（sustainable development）是什么？我们为什么应该重视它？',
    questions: [
      '你在报告中提到气候变化和资源缺乏，就要用尽，你可以再加以说明是什么情况吗？',
      '义安理工学院推出的可持续发展教育与生态系统发展项目，有什么特点？',
      '你自己采取了哪些方法，来参与可持续发展？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6349864661112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-ngee-ann-poly-sustainable-development-2599721',
    hasEmbeddedVideo: true,
  },
  {
    id: 19,
    title: '让孩子安全使用电子设备',
    description: '“首机启航我们行”运动是有必要的。请谈谈你的看法？',
    mainQuestion: '“首机启航我们行”运动是有必要的。请谈谈你的看法？',
    questions: [
      '触爱社会服务推出“首机启航我们行”运动的目的是什么？',
      '你认为网络上哪些内容是对少年最有害？怎样避免接触网络上的有害内容？',
      '怎样才能做到对五岁以下孩童上网时间的掌控？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6349560158112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-first-device-campaign-launch-2581961',
    hasEmbeddedVideo: true,
  },
  {
    id: 20,
    title: '包包清洗和修复需求增加',
    description: '为什么越来越多国人把自己的包包送去清洗和修复呢？',
    mainQuestion: '为什么越来越多国人把自己的包包送去清洗和修复呢？',
    questions: [
      '为什么包包不能自己修补呢？',
      '你心目中有哪些有意义的物件？这些物件都可以修复吗？',
      '你认为要怎样保护或珍惜有意义的物件？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6344476140112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-handbag-cleaning-repairing-service-2550141',
    hasEmbeddedVideo: true,
  },
  {
    id: 21,
    title: '气候变化对我国旅游业的影响',
    description: '本地气候变得更炎热潮湿，会让来我国旅游的外国游客减少。你同意吗？',
    mainQuestion: '本地气候变得更炎热潮湿，会让来我国旅游的外国游客减少。你同意吗？',
    questions: [
      '你在报告中提到，游客可以进行室内活动，如参观不同的博物馆。你可以说说，游客可以在博物馆进行哪一些活动呢？',
      '你认为外国游客会因为本地气候变得更炎热潮湿，不愿意来我国，而到其他的国家去旅行吗？',
      '你认为我们要怎么样继续吸引外国旅客来我国旅游呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6344886311112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-climate-change-impacts-tourism-2543136',
    hasEmbeddedVideo: true,
  },
  {
    id: 22,
    title: '护联中心推出失智症患者日常体验展览',
    description: '护联中心为了帮助失智症患者做出了足够的努力。你同意吗？',
    mainQuestion: '护联中心为了帮助失智症患者做出了足够的努力。你同意吗？',
    questions: [
      '如果让你接触一些失智症患者，你会有什么感受？为什么？',
      '你认为应该如何关心和照顾身边的失智症患者？',
      '有人认为，“打造亲失智症患者的环境，政府起着关键性作用”。你同意吗？为什么？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6344389047112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-aic-dementia-exhibition-2532646',
    hasEmbeddedVideo: true,
  },
  {
    id: 23,
    title: '80%本地年长者有营养不良风险',
    description: '我国老年人的健康是我们必须关切的问题。你同意这个观点吗？',
    mainQuestion: '我国老年人的健康是我们必须关切的问题。你同意这个观点吗？',
    questions: [
      '你在报告中认为“国家在照顾老年人时会面对棘手的问题”请你进一步说明？',
      '你认为家庭医生或社区保健团队会提供什么建议给来寻求帮助的老年人呢？',
      '你刚才说“让老年人时常下厨，烹煮有营养的食物”，你认为容易吗？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6340945368112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-elderly-health-malnutrition-2512106',
    hasEmbeddedVideo: true,
  },
  {
    id: 24,
    title: '糖尿病患者有年轻化趋势',
    description: '你认为要怎么样才能减少年轻人患上糖尿病？',
    mainQuestion: '你认为要怎么样才能减少年轻人患上糖尿病？',
    questions: [
      '你在报告中一开始就提到“很多糖尿病患者都有久坐的习惯”，你自己是否也长时间坐着不动呢？',
      '除了你在报告中说到生理的问题之外，你认为年轻人是否也面对心理健康的问题呢？',
      '你认为年轻人要怎么样“保持活跃的健康生活方式”呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6341095362112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-diabetes-in-young-2503246',
    hasEmbeddedVideo: true,
  },
  {
    id: 25,
    title: '我国将步入超老龄化社会',
    description: '新加坡的超老龄化将给社会带来巨大的挑战。你同意吗？',
    mainQuestion: '新加坡的超老龄化将给社会带来巨大的挑战。你同意吗？',
    questions: [
      '你认为乐龄人士在你的家庭中有什么作用？',
      '我们如何让家中的老人身体和心理更加健康？',
      '有人认为，年长者很难再展现价值，为社区、社会做出贡献。你同意吗？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6340365256112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-ageing-society-2475511',
    hasEmbeddedVideo: true,
  },
  {
    id: 26,
    title: '隐形眼镜包装盒回收计划',
    description: '隐形眼镜包装盒回收计划对环保有积极的影响。你同意吗？',
    mainQuestion: '隐形眼镜包装盒回收计划对环保有积极的影响。你同意吗？',
    questions: [
      '你身边的人会回收隐形眼镜盒吗？为什么？',
      '你认为应该如何鼓励公众回收隐形眼镜盒？',
      '有人认为，回收隐形眼镜盒只是一件小事，没有必要小题大做。你同意吗？为什么？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6340666019112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-contact-lens-blisters-recycling-2465321',
    hasEmbeddedVideo: true,
  },
  {
    id: 27,
    title: '脚踏车销量比疫情前高出30%',
    description: '你会鼓励身边的人买脚踏车当代步工具吗？',
    mainQuestion: '你会鼓励身边的人买脚踏车当代步工具吗？',
    questions: [
      '你为什么会说“增建了脚踏车道，国人能安全地骑脚车，不必在公路上和汽车共用马路”？',
      '你会怎么样鼓励身边的人骑脚踏车呢？',
      '如果他们不想先买脚踏车，你有其他建议给他们吗？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6338677051112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-bicycle-demand-2451506',
    hasEmbeddedVideo: true,
  },
  {
    id: 28,
    title: '餐饮业者因没戴口罩被取缔',
    description: '有必要强制餐饮业员工佩戴口罩？',
    mainQuestion: '有必要强制餐饮业员工佩戴口罩？',
    questions: [
      '你本身有没有遇到过小贩不戴口罩处理食物的情况？你又会怎样做？',
      '你认为食品局更勤密突击检查，会有明显效果吗？',
      '怎样才能使餐饮业员工自觉遵守戴口罩的规定？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6340289215112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-food-handlers-mask-policy-2441666',
    hasEmbeddedVideo: true,
  },
  {
    id: 29,
    title: '我国基础设施无法支持大规模回收',
    description: '我国无充足基础设施来支持大规模回收，因而影响物品的回收和循环。你同意这种说法吗？',
    mainQuestion: '我国无充足基础设施来支持大规模回收，因而影响物品的回收和循环。你同意这种说法吗？',
    questions: [
      '你在报告中提到，“学生从小养成环保的习惯，应该不会过度消费，就不会造成太多浪费”，你可以进一步加以说明吗？',
      '从哪里看得出二手商品越来越受欢迎？',
      '你认为是什么原因让我国年轻一代越来越能接受二手商品呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6336524585112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-textile-recycling-methods-2428281',
    hasEmbeddedVideo: true,
  },
  {
    id: 30,
    title: '更多年轻人加入艺术品投资市场',
    description: '你同意年轻人加入艺术品投资市场吗？',
    mainQuestion: '你同意年轻人加入艺术品投资市场吗？',
    questions: [
      '你在报告中说到“年轻人培养对艺术的热爱与兴趣，这对人类文化遗产的延续有一定的帮助。”你为什么会这么说呢？',
      '为什么你会认为“年轻人投资艺术品能减少投资时遇到的风险”呢？',
      '关于这个话题，你还有什么补充的看法或建议吗？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6333064148112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-millennials-art-buying-2410036',
    hasEmbeddedVideo: true,
  },
  {
    id: 31,
    title: '本地最大康疗花园投入使用',
    description: '我国应该建设更多包容性花园。谈谈你的看法？',
    mainQuestion: '我国应该建设更多包容性花园。谈谈你的看法？',
    questions: [
      '你在报告中说，包容性花园里的多元设施可以让不同年龄层的人在同一个地点进行各自的活动，有助于加强家庭凝聚力。你可以进一步说明吗？',
      '你在报告中说，建设包容性花园有助于把新加坡打造成一个具有包容性的社会。为什么你会这么说呢？',
      '从明年起，国家公园局将与社区团体合作，在包容性花园里联手开办课程和导览活动。对此你有什么建议？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6337205130112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-wellness-garden-2398226',
    hasEmbeddedVideo: true,
  },
  {
    id: 32,
    title: '圣淘沙给弱势群体提供实习和就业机会',
    description: '请你谈谈什么是具包容性的社会？',
    mainQuestion: '请你谈谈什么是具包容性的社会？',
    questions: [
      '你说“大家的声音都会被听到”，能进一步说明吗？',
      '圣淘沙发展局会和社区及家庭发展部，以及新加坡协助残障者自立局合作，打造更包容性的工作场所。你对此有什么看法？',
      '如果你有一位有残疾的同学，你认为作为同班同学，大家可以如何帮助他/她？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6338130144112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-sentosa-msf-sg-enable-2383856',
    hasEmbeddedVideo: true,
  },
  {
    id: 33,
    title: '93%公众支持强制国民服役',
    description: '你支持强制性的国民服役吗？谈谈你的看法？',
    mainQuestion: '你支持强制性的国民服役吗？谈谈你的看法？',
    questions: [
      '你在报告中说，国民服役让年轻人在领导技能方面得到发展。你可以加以说明吗？',
      '如果政府要修改国民服役制度的话，你会提出什么改善建议呢？',
      '你认为男生在入伍前应如何做好准备呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6399463440112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-national-service-survey-2378126',
    hasEmbeddedVideo: true,
  },
  {
    id: 34,
    title: '艺理会推出新艺术拓展蓝图',
    description: '生活中处处都是艺术。请谈谈你的见解？',
    mainQuestion: '生活中处处都是艺术。请谈谈你的见解？',
    questions: [
      '你提到在选择的过程中，也是在做艺术思考。你可以再补充说明一下吗？',
      '对国家艺术理事会的艺术拓展蓝图有什么看法？',
      '你自己有什么艺术方面的经验可以分享呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6336613288112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-national-arts-council-our-sg-arts-plan-2362396',
    hasEmbeddedVideo: true,
  },
  {
    id: 35,
    title: '本地家具业推木匠认证课程',
    description: '新加坡家具工业理事会推出的认证课程能改善本地家具业面对的问题吗？',
    mainQuestion: '新加坡家具工业理事会推出的认证课程能改善本地家具业面对的问题吗？',
    questions: [
      '你在报告中提到参与这项课程能进一步了解它的工作性质，就不会感到那么辛苦。你能否进一步说明呢？',
      '你提到“在职位配对时能表现出专业水平”，怎么样才称得上是专业水平呢？',
      '你认为木工的“专业水平”能怎么运用在你的学习方面呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6080604076001&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-carpenter-certification-2354766',
    hasEmbeddedVideo: true,
  },
  {
    id: 36,
    title: '开放式创新平台助企业找到数码解决方案',
    description: '开放式创新平台有效地为我国企业提出的项目找到数码解决方案。你同意吗？',
    mainQuestion: '开放式创新平台有效地为我国企业提出的项目找到数码解决方案。你同意吗？',
    questions: [
      '你在报告中提到开放式创新平台为超过300个由企业提出的项目，找到数码解决方案。你能举例子加以说明吗？',
      '在资讯通信媒体发展局推出的开放式创新平台上的科技公司能得到哪一些好处？',
      '关于这个话题，你还有什么补充的看法或建议吗？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6081381400001&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-open-innovation-platform-digital-solutions-2339051',
    hasEmbeddedVideo: true,
  },
  {
    id: 37,
    title: '培育我国下一代网络安全专才',
    description: '你认为我国国防部战略资讯科技中心推出的新培训计划，能增强我国应对网络威胁的能力吗？',
    mainQuestion: '你认为我国国防部战略资讯科技中心推出的新培训计划，能增强我国应对网络威胁的能力吗？',
    questions: [
      '你为什么认为应对网络威胁而量身定制的软件就具有一定的针对性和可靠性，必能有效地防御网络攻击？',
      '国人在防止数据被盗取或泄露方面能否尽一份力呢？',
      '关于这个话题，你还有什么补充的看法或建议吗？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6395331736112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-csit-new-programme-for-cyber-security-talents-2291401',
    hasEmbeddedVideo: true,
  },
  {
    id: 38,
    title: '我不善于社交但社交非常重要？',
    description: '你认为在现代社会中，网络和面对面社交都很重要吗？',
    mainQuestion: '你认为在现代社会中，网络和面对面社交都很重要吗？',
    questions: [
      '你在报告中说，面对面社交可以更直接清楚地沟通，感受到对方要传达的信息，避免产生误会。你可以举例加以说明吗？',
      '你在报告中说，网上社交打破时间和空间的限制。你可以举例加以说明吗？',
      '在你看来，为什么一些年轻人会对面对面社交感到恐惧？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6345820242112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-importance-networking-and-socializing-2280226',
    hasEmbeddedVideo: true,
  },
  {
    id: 39,
    title: '三巴旺举办世界地球日活动',
    description: '你认为三巴旺集选区为了配合世界地球日而举办的活动，能提高居民的环保意识吗？',
    mainQuestion: '你认为三巴旺集选区为了配合世界地球日而举办的活动，能提高居民的环保意识吗？',
    questions: [
      '在公园步行两公里怎么样能够提高居民的环保意识呢？',
      '这次的活动怎么样促进小孩子动手的能力呢？',
      '除了视频中提到的活动之外，你认为还有什么方法来提高居民的环保意识呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6081453417001&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-international-earth-day-2268086',
    hasEmbeddedVideo: true,
  },
  {
    id: 40,
    title: '社区急救员过去五年通过应用共为7670起紧急事故提供援助',
    description: '增加社区内自动体外除颤器和灭火器的数量就能提升公众的应急能力。你同意吗？',
    mainQuestion: '增加社区内自动体外除颤器和灭火器的数量就能提升公众的应急能力。你同意吗？',
    questions: [
      '你为什么会说“器材发生故障无法使用就不能提升公众的应急能力”呢？',
      '你能否进一步说明“视频提供的案例数目不能说明增加自动体外除颤器和灭火器就能提升公众的应急能力”？',
      '既然增加设备无法提升公众的应急能力，你认为还有什么方法能提升公众的应急能力呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6356547256112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-aed-myresponder-app-2255596',
    hasEmbeddedVideo: true,
  },
  {
    id: 41,
    title: '虚拟艺术会否成为艺术界主流趋势？',
    description: '你认为虚拟艺术会发展成艺术界的主流趋势吗？',
    mainQuestion: '你认为虚拟艺术会发展成艺术界的主流趋势吗？',
    questions: [
      '你认为沉浸式展览或虚拟艺术，是如何把观众带入艺术家的视角呢？',
      '你为什么会期待虚拟艺术成为艺术界的主流呢？',
      '若有机会，你会带人去参观梵高艺术沉浸式体验展览吗？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6388145131112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-immersive-arts-2246641',
    hasEmbeddedVideo: true,
  },
  {
    id: 42,
    title: '中国共享脚踏车公司进驻本地市场',
    description: '作为交通工具，共享脚踏车的发展和推广值得鼓励。请谈谈你的看法？',
    mainQuestion: '作为交通工具，共享脚踏车的发展和推广值得鼓励。请谈谈你的看法？',
    questions: [
      '你在报告中谈论了共享脚踏车的益处，那你觉得它有什么隐患吗？',
      '根据视频的介绍，共享脚踏车的业者面对怎样的挑战？他们如何应对？',
      '你有使用过共享脚踏车吗？如果有，请你分享你的使用经验。如果没有，你会想尝试使用吗？为什么？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6399903998112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-helloride-shared-bikes-2231626',
    hasEmbeddedVideo: true,
  },
  {
    id: 43,
    title: '保家安民计划每年平均接获1万起通报',
    description: '全国保家安民计划能成功地及时为有需要的国人伸出援手。你同意吗？为什么？',
    mainQuestion: '全国保家安民计划能成功地及时为有需要的国人伸出援手。你同意吗？为什么？',
    questions: [
      '你为什么会认为越来越多国人掌握急救技能，及时帮助有需要的公众的机会也就更高呢？',
      '在报告中，你提到在社区急救圆桌会议中，大家会找出计划的漏洞和机遇。你认为此计划有哪些漏洞呢？',
      '你会参与全国保家安民计划吗？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6390418032112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-sgsecure-2209641',
    hasEmbeddedVideo: true,
  },
  {
    id: 44,
    title: '年轻型失智症患者增加',
    description: '为什么需要增加辅助活动来帮助年轻型失智症患者？',
    mainQuestion: '为什么需要增加辅助活动来帮助年轻型失智症患者？',
    questions: [
      '你为什么会认为年轻型失智症患者的病症复杂，需要增加辅助活动来帮助他们呢？',
      '你认为要举办哪一类活动，才能帮助年轻型失智症患者保持活跃呢？',
      '你认为要怎么样预防过早患上失智症？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6361447736112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-young-onset-dementia-2209221',
    hasEmbeddedVideo: true,
  },
  {
    id: 45,
    title: '10座商场加入建屋局应用',
    description: '你同意建屋局在另外十座商场推出建屋局的应用程序吗？',
    mainQuestion: '你同意建屋局在另外十座商场推出建屋局的应用程序吗？',
    questions: [
      '你在报告中说到“只要顾客使用应用程序，来到店里时已经知道要买什么了，在时间方面缩短了很多。”请你说明这样为什么能缩短时间呢？',
      '为什么你会认为商家使用应用程序让更多顾客很快获得产品的讯息，被吸引去消费，商家就愿意使用这款应用程序呢？',
      '除了建屋局推出的应用程序，你认为还有什么方法让商家吸引顾客上门消费呢？',
    ],
    videoUrl: 'https://players.brightcove.net/6057984932001/default_default/index.html?videoId=6396628484112&autoplay=true&muted=true',
    sourceUrl: 'https://soyoung.8world.com/fun-learning/oral-hdb-shopperlink-retailerlink-app-2193566',
    hasEmbeddedVideo: true,
  },
];

export function getOLevelOralSet(id: number): OLevelOralSet | undefined {
  return OLEVEL_ORAL_SETS.find((s) => s.id === id);
}
